/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from "bn.js";
import { Contract, ContractOptions, EventOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { TransactionObject, ContractEvent, Callback } from "./types";

export class ArianeeLost extends Contract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  );
  clone(): ArianeeLost;
  methods: {
    setLost(_tokenId: number | string): TransactionObject<void>;

    unsetLost(_tokenId: number | string): TransactionObject<void>;

    isLost(_tokenId: number | string): TransactionObject<boolean>;

    smartAsset(): TransactionObject<string>;
  };
  events: {
    Lost: ContractEvent<BN>;
    Retrieved: ContractEvent<BN>;
    allEvents: (options?: EventOptions, cb?: Callback<EventLog>) => any;
  };
}
