/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from "bn.js";
import {Contract, ContractOptions } from "web3-eth-contract";

import {TransactionObject} from "./types";

export class Aria extends Contract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  );
  clone(): Aria;
  methods: {
    supportsInterface(
      _interfaceID: string | number[]
    ): TransactionObject<boolean>;

    balanceOf(_owner: string): TransactionObject<BN>;

    allowance(_owner: string, _spender: string): TransactionObject<BN>;

    approve(
      _spender: string,
      _value: number | string
    ): TransactionObject<boolean>;

    transferFrom(
      _from: string,
      _to: string,
      _value: number | string
    ): TransactionObject<boolean>;

    transfer(_to: string, _value: number | string): TransactionObject<boolean>;

    name(): TransactionObject<string>;
    totalSupply(): TransactionObject<BN>;
    decimals(): TransactionObject<BN>;
    symbol(): TransactionObject<string>;

  };

}
