/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from "bn.js";
import Contract, { contractOptions } from "web3/eth/contract";
import { EventLog, Callback, EventEmitter } from "web3/types";
import { TransactionObject, BlockType } from "web3/eth/types";
import { ContractEvent } from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export class ArianeeSmartAsset extends Contract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: contractOptions
  );
  clone(): ArianeeSmartAsset;
  methods: {
    supportsInterface(
      _interfaceID: string | number[]
    ): TransactionObject<boolean>;

    isTokenValid(
      _tokenId: number | string,
      _hash: string | number[],
      _tokenType: number | string,
      _signature: string | number[]
    ): TransactionObject<boolean>;

    getApproved(_tokenId: number | string): TransactionObject<string>;

    tokenOfOwnerByIndex(
      _owner: string,
      _index: number | string
    ): TransactionObject<BN>;

    tokenByIndex(_index: number | string): TransactionObject<BN>;

    tokenCreation(_tokenId: number | string): TransactionObject<BN>;

    ownerOf(_tokenId: number | string): TransactionObject<string>;

    recoveryRequestOpen(_tokenId: number | string): TransactionObject<boolean>;

    isAble(
      _target: string,
      _ability: number | string
    ): TransactionObject<boolean>;

    balanceOf(_owner: string): TransactionObject<BN>;

    tokenImprint(_tokenId: number | string): TransactionObject<string>;

    canOperate(
      _tokenId: number | string,
      _operator: string
    ): TransactionObject<boolean>;

    issuerOf(_tokenId: number | string): TransactionObject<string>;

    getRewards(_tokenId: number | string): TransactionObject<BN>;

    tokenURI(_tokenId: number | string): TransactionObject<string>;

    tokenHashedAccess(
      _tokenId: number | string,
      _tokenType: number | string
    ): TransactionObject<string>;

    tokenRecoveryDate(_tokenId: number | string): TransactionObject<BN>;

    isApprovedForAll(
      _owner: string,
      _operator: string
    ): TransactionObject<boolean>;

    isRequestable(_tokenId: number | string): TransactionObject<boolean>;

    approve(
      _approved: string,
      _tokenId: number | string
    ): TransactionObject<void>;

    validRecoveryRequest(_tokenId: number | string): TransactionObject<void>;

    updateTokenURI(
      _tokenId: number | string,
      _uri: string
    ): TransactionObject<void>;

    transferFrom(
      _from: string,
      _to: string,
      _tokenId: number | string
    ): TransactionObject<void>;

    reserveToken(
      _tokenId: number | string,
      _to: string,
      _rewards: number | string
    ): TransactionObject<void>;

    setUriBase(_newURIBase: string): TransactionObject<void>;

    unpause(): TransactionObject<void>;

    safeTransferFrom(
      _from: string,
      _to: string,
      _tokenId: number | string
    ): TransactionObject<void>;

    setStoreAddress(_storeAddress: string): TransactionObject<void>;

    assignAbilities(
      _target: string,
      _abilities: (number | string)[]
    ): TransactionObject<void>;

    pause(): TransactionObject<void>;

    revokeAbilities(
      _target: string,
      _abilities: (number | string)[]
    ): TransactionObject<void>;

    setWhitelistAddress(_whitelistAddres: string): TransactionObject<void>;

    setApprovalForAll(
      _operator: string,
      _approved: boolean
    ): TransactionObject<void>;

    recoverTokenToIssuer(_tokenId: number | string): TransactionObject<void>;

    addTokenAccess(
      _tokenId: number | string,
      _key: string,
      _enable: boolean,
      _tokenType: number | string
    ): TransactionObject<void>;

    requestToken(
      _tokenId: number | string,
      _hash: string | number[],
      _keepRequestToken: boolean,
      _newOwner: string,
      _signature: string | number[]
    ): TransactionObject<{
      reward: BN;
      message: string;
      0: BN;
      1: string;
    }>;

    hydrateToken(
      _tokenId: number | string,
      _imprint: string | number[],
      _uri: string,
      _initialKey: string,
      _tokenRecoveryTimestamp: number | string,
      _initialKeyIsRequestKey: boolean,
      _owner: string
    ): TransactionObject<BN>;

    transferOwnership(_newOwner: string): TransactionObject<void>;

    updateRecoveryRequest(
      _tokenId: number | string,
      _active: boolean
    ): TransactionObject<void>;

    name(): TransactionObject<string>;
    totalSupply(): TransactionObject<BN>;
    paused(): TransactionObject<boolean>;
    owner(): TransactionObject<string>;
    symbol(): TransactionObject<string>;
    uriBase(): TransactionObject<string>;
  };
  events: {
    SetAddress: ContractEvent<{
      _addressType: string;
      _newAddress: string;
      0: string;
      1: string;
    }>;
    Hydrated: ContractEvent<{
      _tokenId: BN;
      _imprint: string;
      _uri: string;
      _initialKey: string;
      _tokenRecoveryTimestamp: BN;
      _initialKeyIsRequestKey: boolean;
      _tokenCreation: BN;
      0: BN;
      1: string;
      2: string;
      3: string;
      4: BN;
      5: boolean;
      6: BN;
    }>;
    RecoveryRequestUpdated: ContractEvent<{
      _tokenId: BN;
      _active: boolean;
      0: BN;
      1: boolean;
    }>;
    TokenRecovered: ContractEvent<BN>;
    TokenURIUpdated: ContractEvent<{
      _tokenId: BN;
      URI: string;
      0: BN;
      1: string;
    }>;
    tokenAccessAdded: ContractEvent<{
      _tokenId: BN;
      _encryptedTokenKey: string;
      _enable: boolean;
      _tokenType: BN;
      0: BN;
      1: string;
      2: boolean;
      3: BN;
    }>;
    Pause: ContractEvent<{}>;
    Unpause: ContractEvent<{}>;
    OwnershipTransferred: ContractEvent<{
      previousOwner: string;
      newOwner: string;
      0: string;
      1: string;
    }>;
    AssignAbility: ContractEvent<{
      _target: string;
      _ability: BN;
      0: string;
      1: BN;
    }>;
    RevokeAbility: ContractEvent<{
      _target: string;
      _ability: BN;
      0: string;
      1: BN;
    }>;
    Transfer: ContractEvent<{
      _from: string;
      _to: string;
      _tokenId: BN;
      0: string;
      1: string;
      2: BN;
    }>;
    Approval: ContractEvent<{
      _owner: string;
      _approved: string;
      _tokenId: BN;
      0: string;
      1: string;
      2: BN;
    }>;
    ApprovalForAll: ContractEvent<{
      _owner: string;
      _operator: string;
      _approved: boolean;
      0: string;
      1: string;
      2: boolean;
    }>;
    allEvents: (
      options?: EventOptions,
      cb?: Callback<EventLog>
    ) => EventEmitter;
  };
}
